
const express = require('express')
const dotenv = require('dotenv')
dotenv.config({path:"config/.env"})
const cors = require('cors')
const router = require('./routes/routes')
const app = express()
require('./models/db')
app.use(express.json())
app.use(cors())
app.use('/api/tasks' , router)
app.listen(process.env.PORT , err => {
    if(err) console.log(err)
    console.log(`Server is started at PORT number :${process.env.PORT} `)
})